"""empty message

Revision ID: 8fd9a43312fe
Revises: 
Create Date: 2019-04-10 16:10:37.145543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd9a43312fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('cid', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'course', ['cid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'cid')
    # ### end Alembic commands ###
